[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Т.к. приложение SPA, то index.html один и чтобы не было ошибки netlify при обновлении страницы, необходимо указать редиректы, чтобы с любого маршрута было проксирование в index.html файлик